//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Type { get; set; }
        public string Species { get; set; }
        public Nullable<System.DateTime> Born { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Color { get; set; }
    
        public virtual Owner Owner1 { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
