//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int Animal { get; set; }
        public string Vet { get; set; }
        public System.DateTime Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Vet Vet1 { get; set; }
    }
}
